In [127]:
import pandas as pd
import numpy as np 
import json
from datetime import datetime
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.preprocessing import OneHotEncoder

In [2]:
synopsis = pd.read_csv('anime_with_synopsis.csv')

In [3]:
synopsis

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...
...,...,...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",No synopsis information has been added to this...
16210,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",ko is a typical high school student whose life...
16211,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Sequel to Higurashi no Naku Koro ni Gou .
16212,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",New Yama no Susume anime.
16213,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Solar calendar year 2020: grotesque organisms ...

In [4]:
synopsis.dtypes

MAL_ID        int64
Name         object
Score        object
Genres       object
sypnopsis    object
dtype: object

In [150]:
anime = pd.read_csv('anime.csv')

In [151]:
anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,Unknown,Unknown,Unknown,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [212]:
anime_list = pd.read_csv('animelist_1mil.csv')

In [213]:
anime_list

        user_id  anime_id  rating  watching_status  watched_episodes
0        336145      2251      10                2                13
1        343247      2787       9                2                24
2        130592       235       9                1               752
3         38258     10572       0                3                 1
4        196188     22729       8                2                12
...         ...       ...     ...              ...               ...
999995    82894     18679       8                2                24
999996    78032     12549       0                2                12
999997    67572     37450       0                6                 0
999998   129806     31442       0                6                 0
999999   280824     38778       0                6                 0

[1000000 rows x 5 columns]

In [9]:
anime_list.dtypes

user_id             int64
anime_id            int64
rating              int64
watching_status     int64
watched_episodes    int64
dtype: object

In [12]:
anime_list.isna().sum()

user_id             0
anime_id            0
rating              0
watching_status     0
watched_episodes    0
dtype: int64

In [13]:
anime.isna().sum()

MAL_ID           0
Name             0
Score            0
Genres           0
English name     0
Japanese name    0
Type             0
Episodes         0
Aired            0
Premiered        0
Producers        0
Licensors        0
Studios          0
Source           0
Duration         0
Rating           0
Ranked           0
Popularity       0
Members          0
Favorites        0
Watching         0
Completed        0
On-Hold          0
Dropped          0
Plan to Watch    0
Score-10         0
Score-9          0
Score-8          0
Score-7          0
Score-6          0
Score-5          0
Score-4          0
Score-3          0
Score-2          0
Score-1          0
dtype: int64

In [15]:
#anime_list_1mil = anime_list.sample(n=1000000, replace=False, random_state=42)

In [17]:
#anime_list_1mil.to_csv('animelist_1mil.csv', index=False)

In [18]:
#anime_list.to_csv('animelist_cleaned.csv', index=False)

In [19]:
anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,229170.0,182126.0,131625.0,62330.0,20688.0,8904.0,3184.0,1357.0,741.0,1580.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,30043.0,49201.0,49505.0,22632.0,5805.0,1877.0,577.0,221.0,109.0,379.0
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,50229.0,75651.0,86142.0,49432.0,15376.0,5838.0,1965.0,664.0,316.0,533.0
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,2182.0,4806.0,10128.0,11618.0,5709.0,2920.0,1083.0,353.0,164.0,131.0
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,312.0,529.0,1242.0,1713.0,1068.0,634.0,265.0,83.0,50.0,27.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,Unknown,Unknown,Unknown,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [26]:
anime[anime['Score'] == 'Unknown']

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Score-10,Score-9,Score-8,Score-7,Score-6,Score-5,Score-4,Score-3,Score-2,Score-1
1404,1547,Obake no Q-tarou,Unknown,"Comedy, School, Slice of Life, Supernatural",Unknown,オバケのＱ太郎,TV,96,"Aug 29, 1965 to Jun 28, 1967",Summer 1965,...,8.0,5.0,6.0,20.0,28.0,31.0,6.0,6.0,2.0,10.0
1504,1656,PostPet Momobin,Unknown,"Comedy, Kids",Unknown,ポストペットモモ便,TV,24,"Jul 4, 2004 to Jan 9, 2005",Summer 2004,...,7.0,2.0,6.0,13.0,17.0,22.0,15.0,12.0,7.0,10.0
1578,1739,Shibawanko no Wa no Kokoro,Unknown,Kids,Unknown,しばわんこの和のこころ,TV,80,"Apr 5, 2006 to Mar 14, 2007",Spring 2006,...,6.0,4.0,23.0,28.0,18.0,17.0,1.0,3.0,Unknown,8.0
1699,1863,Silk Road Shounen Yuuto,Unknown,"Adventure, Fantasy, Historical",Unknown,シルクロード少年 ユート,TV,26,"Sep 16, 2006 to Mar 24, 2007",Fall 2006,...,3.0,1.0,2.0,9.0,5.0,9.0,3.0,1.0,2.0,3.0
1893,2073,Hengen Taima Yakou Karura Mau! Sendai Kokeshi ...,Unknown,"Horror, Shoujo",Unknown,変幻退魔夜行 カルラ舞う！ 仙台小芥子怨歌,OVA,6,"Sep 14, 1990 to Mar 8, 1991",Unknown,...,10.0,3.0,14.0,26.0,27.0,19.0,10.0,3.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,Unknown,Unknown,Unknown,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17558,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17559,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,1.0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17560,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
17561,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [20]:
anime.to_csv('anime_cleaned.csv', index=False)

In [22]:
synopsis = pd.read_csv('anime_with_synopsis.csv')

In [23]:
synopsis

,MAL_ID,Name,Score,Genres,sypnopsis
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space","In the year 2071, humanity has colonized sever..."
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space","other day, another bounty—such is the life of ..."
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen","Vash the Stampede is the man with a $$60,000,0..."
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ...",ches are individuals with special powers like ...
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural",It is the dark century and the people are suff...
...,...,...,...,...,...
16209,48481,Daomu Biji Zhi Qinling Shen Shu,Unknown,"Adventure, Mystery, Supernatural",No synopsis information has been added to this...
16210,48483,Mieruko-chan,Unknown,"Comedy, Horror, Supernatural",ko is a typical high school student whose life...
16211,48488,Higurashi no Naku Koro ni Sotsu,Unknown,"Mystery, Dementia, Horror, Psychological, Supe...",Sequel to Higurashi no Naku Koro ni Gou .
16212,48491,Yama no Susume: Next Summit,Unknown,"Adventure, Slice of Life, Comedy",New Yama no Susume anime.
16213,48492,Scarlet Nexus,Unknown,"Action, Fantasy",Solar calendar year 2020: grotesque organisms ...

In [24]:
ratings = pd.read_csv('rating_complete.csv')

In [25]:
ratings.to_csv()

          user_id  anime_id  rating
0               0       430       9
1               0      1004       5
2               0      3010       7
3               0       570       7
4               0      2762       9
...           ...       ...     ...
57633273   353404       502       8
57633274   353404       987       4
57633275   353404       225       8
57633276   353404       243       7
57633277   353404       896       7

[57633278 rows x 3 columns]

In [221]:
watching_status = pd.read_csv('watching_status.csv')

# Data Preparation

### Fix anime scores, replace 'Unknown' values with np.nan and then mean impute

In [152]:
anime.dtypes

MAL_ID            int64
Name             object
Score            object
Genres           object
English name     object
Japanese name    object
Type             object
Episodes         object
Aired            object
Premiered        object
Producers        object
Licensors        object
Studios          object
Source           object
Duration         object
Rating           object
Ranked           object
Popularity        int64
Members           int64
Favorites         int64
Watching          int64
Completed         int64
On-Hold           int64
Dropped           int64
Plan to Watch     int64
Score-10         object
Score-9          object
Score-8          object
Score-7          object
Score-6          object
Score-5          object
Score-4          object
Score-3          object
Score-2          object
Score-1          object
dtype: object

In [153]:
# Replace Unknown Values
anime['Score'] = anime['Score'].replace({'Unknown': np.nan})
anime['Score'] = anime['Score'].astype('float')

In [154]:
anime['Score'].dtypes

dtype('float64')

In [155]:
anime['Score'].isna().sum()

5141

In [156]:
# We may have to change this imputation method if it impacts the model too much
anime['Score'] = anime['Score'].fillna(anime['Score'].mean())

In [157]:
anime['Score']

0        8.780000
1        8.390000
2        8.240000
3        7.270000
4        6.980000
           ...
17557    6.509999
17558    6.509999
17559    6.509999
17560    6.509999
17561    6.509999
Name: Score, Length: 17562, dtype: float64

### Feature Days Since Aired
Pull the first date from Aired, convert to datetime and get timedelta in days

In [158]:
anime['days_since_aired'] = anime['Aired'].str.split(' to ', expand=True).iloc[:, 0]

In [159]:
# Remove spaces left and right
anime['days_since_aired'] = anime['days_since_aired'].str.strip()

In [160]:
# Fix date format issues
anime['days_since_aired'] = anime['days_since_aired'].str.replace('^\w{3}, \d{4}', lambda x: x[0][0:3] + ' 1, ' + x[0][5:9], regex=True)
anime['days_since_aired'] = anime['days_since_aired'].str.replace('^\d{4}', lambda x: 'Jan 1, ' + x[0], regex=True)
anime['days_since_aired']

0         Apr 3, 1998
1         Sep 1, 2001
2         Apr 1, 1998
3         Jul 2, 2002
4        Sep 30, 2004
             ...
17557     Apr 4, 2021
17558     Jan 1, 2021
17559     Jul 1, 2021
17560         Unknown
17561     Jul 1, 2021
Name: days_since_aired, Length: 17562, dtype: object

In [161]:
anime['days_since_aired'] = anime['days_since_aired'].replace('Unknown', np.nan)
anime['days_since_aired']

0         Apr 3, 1998
1         Sep 1, 2001
2         Apr 1, 1998
3         Jul 2, 2002
4        Sep 30, 2004
             ...
17557     Apr 4, 2021
17558     Jan 1, 2021
17559     Jul 1, 2021
17560             NaN
17561     Jul 1, 2021
Name: days_since_aired, Length: 17562, dtype: object

In [162]:
anime['days_since_aired'] = pd.to_datetime(anime['days_since_aired'], format='%b %d, %Y')

In [163]:
anime['days_since_aired'] = anime['days_since_aired'].fillna(pd.datetime.now())

/opt/anaconda3/envs/datasci/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  """Entry point for launching an IPython kernel.

In [164]:
anime['days_since_aired']

0       1998-04-03 00:00:00.000000
1       2001-09-01 00:00:00.000000
2       1998-04-01 00:00:00.000000
3       2002-07-02 00:00:00.000000
4       2004-09-30 00:00:00.000000
                   ...
17557   2021-04-04 00:00:00.000000
17558   2021-01-01 00:00:00.000000
17559   2021-07-01 00:00:00.000000
17560   2022-03-31 10:05:07.831232
17561   2021-07-01 00:00:00.000000
Name: days_since_aired, Length: 17562, dtype: datetime64[ns]

### Get Time Delta in days

In [165]:
anime['days_since_aired'] = (pd.datetime.now() - anime['days_since_aired']).dt.days

/opt/anaconda3/envs/datasci/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: The pandas.datetime class is deprecated and will be removed from pandas in a future version. Import from datetime module instead.
  """Entry point for launching an IPython kernel.

In [166]:
anime['days_since_aired']

0        8763
1        7516
2        8765
3        7212
4        6391
         ...
17557     361
17558     454
17559     273
17560       0
17561     273
Name: days_since_aired, Length: 17562, dtype: int64

# One Hot Encode Genres

In [167]:
genre_list = anime['Genres'].apply(lambda x: x.split(', '))

In [168]:
# Unique Genre
list(set(genre_list.sum()))

['Dementia',
 'Shounen Ai',
 'Adventure',
 'Music',
 'Martial Arts',
 'Kids',
 'Sports',
 'Action',
 'Cars',
 'Hentai',
 'Slice of Life',
 'Vampire',
 'Seinen',
 'Thriller',
 'Romance',
 'Samurai',
 'Historical',
 'Drama',
 'Unknown',
 'Psychological',
 'Comedy',
 'Mystery',
 'Josei',
 'Military',
 'Ecchi',
 'Magic',
 'Supernatural',
 'Yaoi',
 'Shounen',
 'Sci-Fi',
 'Super Power',
 'Demons',
 'Parody',
 'Horror',
 'Police',
 'Fantasy',
 'Game',
 'Shoujo',
 'Harem',
 'School',
 'Space',
 'Mecha',
 'Shoujo Ai',
 'Yuri']

In [169]:
mlb = MultiLabelBinarizer()
ohe = pd.DataFrame(mlb.fit_transform(genre_list), columns=mlb.classes_, index=genre_list.index)

In [170]:
anime = pd.concat([anime, ohe], axis=1)

In [171]:
anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Slice of Life,Space,Sports,Super Power,Supernatural,Thriller,Unknown,Vampire,Yaoi,Yuri
0,1,Cowboy Bebop,8.780000,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,0,1,0,0,0,0,0,0,0,0
1,5,Cowboy Bebop: Tengoku no Tobira,8.390000,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,0,1,0,0,0,0,0,0,0,0
2,6,Trigun,8.240000,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,0,0,0,0,0,0,0,0,0,0
3,7,Witch Hunter Robin,7.270000,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,0,0,0,0,1,0,0,0,0,0
4,8,Bouken Ou Beet,6.980000,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,6.509999,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,0,0,0,0,1,0,0,0,0,0
17558,48483,Mieruko-chan,6.509999,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,0,0,0,0,1,0,0,0,0,0
17559,48488,Higurashi no Naku Koro ni Sotsu,6.509999,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,0,0,0,0,1,1,0,0,0,0
17560,48491,Yama no Susume: Next Summit,6.509999,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,1,0,0,0,0,0,0,0,0,0
17561,48492,Scarlet Nexus,6.509999,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,0,0,0,0,0,0,0,0,0,0

### One hot encode Type

In [172]:
anime['Type'].unique()

array(['TV', 'Movie', 'OVA', 'Special', 'ONA', 'Music', 'Unknown'],
      dtype=object)

In [173]:
anime['Type'] = anime['Type'].replace({'Unknown': 'Other'})

In [174]:
enc = OneHotEncoder(handle_unknown='ignore', sparse=False)
type_ohe = pd.DataFrame(enc.fit_transform(anime[['Type']]), columns=list(enc.categories_[0]))

In [175]:
type_ohe

       Movie  Music  ONA  OVA  Other  Special   TV
0        0.0    0.0  0.0  0.0    0.0      0.0  1.0
1        1.0    0.0  0.0  0.0    0.0      0.0  0.0
2        0.0    0.0  0.0  0.0    0.0      0.0  1.0
3        0.0    0.0  0.0  0.0    0.0      0.0  1.0
4        0.0    0.0  0.0  0.0    0.0      0.0  1.0
...      ...    ...  ...  ...    ...      ...  ...
17557    0.0    0.0  1.0  0.0    0.0      0.0  0.0
17558    0.0    0.0  0.0  0.0    0.0      0.0  1.0
17559    0.0    0.0  0.0  0.0    0.0      0.0  1.0
17560    0.0    0.0  0.0  0.0    0.0      0.0  1.0
17561    0.0    0.0  0.0  0.0    0.0      0.0  1.0

[17562 rows x 7 columns]

In [176]:
# Concat
anime = pd.concat([anime, type_ohe], axis=1)

In [177]:
anime

,MAL_ID,Name,Score,Genres,English name,Japanese name,Type,Episodes,Aired,Premiered,...,Vampire,Yaoi,Yuri,Movie,Music,ONA,OVA,Other,Special,TV
0,1,Cowboy Bebop,8.780000,"Action, Adventure, Comedy, Drama, Sci-Fi, Space",Cowboy Bebop,カウボーイビバップ,TV,26,"Apr 3, 1998 to Apr 24, 1999",Spring 1998,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,5,Cowboy Bebop: Tengoku no Tobira,8.390000,"Action, Drama, Mystery, Sci-Fi, Space",Cowboy Bebop:The Movie,カウボーイビバップ 天国の扉,Movie,1,"Sep 1, 2001",Unknown,...,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
2,6,Trigun,8.240000,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen",Trigun,トライガン,TV,26,"Apr 1, 1998 to Sep 30, 1998",Spring 1998,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,7,Witch Hunter Robin,7.270000,"Action, Mystery, Police, Supernatural, Drama, ...",Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),TV,26,"Jul 2, 2002 to Dec 24, 2002",Summer 2002,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,8,Bouken Ou Beet,6.980000,"Adventure, Fantasy, Shounen, Supernatural",Beet the Vandel Buster,冒険王ビィト,TV,52,"Sep 30, 2004 to Sep 29, 2005",Fall 2004,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,Daomu Biji Zhi Qinling Shen Shu,6.509999,"Adventure, Mystery, Supernatural",Unknown,盗墓笔记之秦岭神树,ONA,Unknown,"Apr 4, 2021 to ?",Unknown,...,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
17558,48483,Mieruko-chan,6.509999,"Comedy, Horror, Supernatural",Unknown,見える子ちゃん,TV,Unknown,2021 to ?,Unknown,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17559,48488,Higurashi no Naku Koro ni Sotsu,6.509999,"Mystery, Dementia, Horror, Psychological, Supe...",Higurashi:When They Cry – SOTSU,ひぐらしのなく頃に卒,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17560,48491,Yama no Susume: Next Summit,6.509999,"Adventure, Slice of Life, Comedy",Unknown,ヤマノススメ Next Summit,TV,Unknown,Unknown,Unknown,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
17561,48492,Scarlet Nexus,6.509999,"Action, Fantasy",Unknown,SCARLET NEXUS,TV,Unknown,"Jul, 2021 to ?",Summer 2021,...,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### Rating Ordinal Encoding

Note that Unknown variables are also grouped along with the most severe rating, just in case. Don't want to accidentally recommend a Adult title if one of the Unknown rating is an adult title. It would be bad to recommend an adult title to the wrong audience

In [181]:
anime['Rating'].unique()

array(['R - 17+ (violence & profanity)', 'PG-13 - Teens 13 or older',
       'PG - Children', 'R+ - Mild Nudity', 'G - All Ages', 'Rx - Hentai',
       'Unknown'], dtype=object)

In [182]:
# Order G to Adult from 1-6
anime['Rating'] = anime['Rating'].replace({'G - All Ages': 1, 'PG - Children': 2, 
                                           'PG-13 - Teens 13 or older': 3, 'R+ - Mild Nudity': 4,
                                           'R - 17+ (violence & profanity)': 5, 'Rx - Hentai': 6,
                                           'Unknown': 6})

In [184]:
anime['Rating']

0        5
1        5
2        3
3        3
4        2
        ..
17557    6
17558    6
17559    5
17560    3
17561    6
Name: Rating, Length: 17562, dtype: int64

## Merging dataframes

In [188]:
# First subset the anime table
anime_cols = ['MAL_ID', 'Score', 'Episodes', 'Rating', 'Ranked', 'Popularity',
       'Members', 'Score-10', 'Score-9', 'Score-8', 'Score-7', 'Score-6',
       'Score-5', 'Score-4', 'Score-3', 'Score-2', 'Score-1',
       'days_since_aired', 'Action', 'Adventure', 'Cars', 'Comedy', 'Dementia',
       'Demons', 'Drama', 'Ecchi', 'Fantasy', 'Game', 'Harem', 'Hentai',
       'Historical', 'Horror', 'Josei', 'Kids', 'Magic', 'Martial Arts',
       'Mecha', 'Military', 'Music', 'Mystery', 'Parody', 'Police',
       'Psychological', 'Romance', 'Samurai', 'School', 'Sci-Fi', 'Seinen',
       'Shoujo', 'Shoujo Ai', 'Shounen', 'Shounen Ai', 'Slice of Life',
       'Space', 'Sports', 'Super Power', 'Supernatural', 'Thriller', 'Unknown',
       'Vampire', 'Yaoi', 'Yuri', 'Movie', 'Music', 'ONA', 'OVA', 'Other',
       'Special', 'TV']

anime_subset = anime[anime_cols]

In [190]:
# Global replace 'Unknown'
anime_subset = anime_subset.replace({'Unknown': np.nan})

### Imputation

In [192]:
anime_subset

,MAL_ID,Score,Episodes,Rating,Ranked,Popularity,Members,Score-10,Score-9,Score-8,...,Yaoi,Yuri,Movie,Music,Music,ONA,OVA,Other,Special,TV
0,1,8.780000,26,5,28.0,39,1251960,229170.0,182126.0,131625.0,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
1,5,8.390000,1,5,159.0,518,273145,30043.0,49201.0,49505.0,...,0,0,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0
2,6,8.240000,26,3,266.0,201,558913,50229.0,75651.0,86142.0,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
3,7,7.270000,26,3,2481.0,1467,94683,2182.0,4806.0,10128.0,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
4,8,6.980000,52,2,3710.0,4369,13224,312.0,529.0,1242.0,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,6.509999,NaN,6,NaN,13116,354,NaN,NaN,NaN,...,0,0,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0
17558,48483,6.509999,NaN,6,NaN,17562,7010,NaN,NaN,NaN,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
17559,48488,6.509999,NaN,5,NaN,17558,11309,1.0,NaN,NaN,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
17560,48491,6.509999,NaN,3,NaN,17565,1386,NaN,NaN,NaN,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0
17561,48492,6.509999,NaN,6,NaN,17563,310,NaN,NaN,NaN,...,0,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0

In [203]:
anime_subset['Episodes'] = anime_subset['Episodes'].fillna(anime_subset['Episodes'].median())
anime_subset['Ranked'] = anime_subset['Ranked'].fillna(anime_subset['Ranked'].median())

for s in range(1, 11):
    anime_subset['Score-' + str(s)] = anime_subset['Score-' + str(s)].fillna(anime_subset['Score-' + str(s)].median())

In [204]:
anime_subset

,MAL_ID,Score,Episodes,Rating,Ranked,Popularity,Members,Score-10,Score-9,Score-8,...,Yuri,Movie,Music,Music,ONA,OVA,Other,Special,TV,Episode
0,1,8.780000,26,5,28.0,39,1251960,229170.0,182126.0,131625.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,26
1,5,8.390000,1,5,159.0,518,273145,30043.0,49201.0,49505.0,...,0,1.0,0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,6,8.240000,26,3,266.0,201,558913,50229.0,75651.0,86142.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,26
3,7,7.270000,26,3,2481.0,1467,94683,2182.0,4806.0,10128.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,26
4,8,6.980000,52,2,3710.0,4369,13224,312.0,529.0,1242.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17557,48481,6.509999,2.0,6,7896.0,13116,354,39.0,71.0,92.0,...,0,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,2.0
17558,48483,6.509999,2.0,6,7896.0,17562,7010,39.0,71.0,92.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
17559,48488,6.509999,2.0,5,7896.0,17558,11309,1.0,71.0,92.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
17560,48491,6.509999,2.0,3,7896.0,17565,1386,39.0,71.0,92.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
17561,48492,6.509999,2.0,6,7896.0,17563,310,39.0,71.0,92.0,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,2.0

In [205]:
anime_subset.isna().sum()

MAL_ID      0
Score       0
Episodes    0
Rating      0
Ranked      0
           ..
OVA         0
Other       0
Special     0
TV          0
Episode     0
Length: 72, dtype: int64

In [214]:
# Rename rating in anime_list to prevent confusion
anime_list.rename(columns={'rating': 'user_rating'}, inplace=True)

In [223]:
anime_list = pd.merge(anime_list, watching_status, left_on='watching_status', right_on='status')

In [224]:
anime_list

,user_id,anime_id,user_rating,watching_status,watched_episodes,status_x,description_x,status_y,description_y
0,336145,2251,10,2,13,2,Completed,2,Completed
1,343247,2787,9,2,24,2,Completed,2,Completed
2,196188,22729,8,2,12,2,Completed,2,Completed
3,161132,1119,7,2,1,2,Completed,2,Completed
4,175224,20909,6,2,7,2,Completed,2,Completed
...,...,...,...,...,...,...,...,...,...
999991,315329,16,6,4,9,4,Dropped,4,Dropped
999992,20341,1887,0,4,3,4,Dropped,4,Dropped
999993,5720,18679,4,4,1,4,Dropped,4,Dropped
999994,291821,4898,0,4,0,4,Dropped,4,Dropped
999995,173775,11785,0,4,2,4,Dropped,4,Dropped

In [225]:
processed_df = pd.merge(anime_list, anime_subset, left_on='anime_id', right_on='MAL_ID')

In [226]:
processed_df

,user_id,anime_id,user_rating,watching_status,watched_episodes,status_x,description_x,status_y,description_y,MAL_ID,...,Yuri,Movie,Music,Music,ONA,OVA,Other,Special,TV,Episode
0,336145,2251,10,2,13,2,Completed,2,Completed,2251,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,13
1,228773,2251,9,2,13,2,Completed,2,Completed,2251,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,13
2,61090,2251,10,2,13,2,Completed,2,Completed,2251,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,13
3,26848,2251,9,2,13,2,Completed,2,Completed,2251,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,13
4,195185,2251,8,2,13,2,Completed,2,Completed,2251,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999991,300428,13503,0,4,0,4,Dropped,4,Dropped,13503,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,11
999992,30459,34369,0,4,0,4,Dropped,4,Dropped,34369,...,0,0.0,0,0.0,0.0,0.0,0.0,1.0,0.0,5
999993,275530,7779,0,4,0,4,Dropped,4,Dropped,7779,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,52
999994,272555,40406,0,4,0,4,Dropped,4,Dropped,40406,...,0,0.0,0,0.0,0.0,0.0,0.0,0.0,1.0,16
999995,300428,35037,0,4,0,4,Dropped,4,Dropped,35037,...,0,0.0,0,0.0,0.0,1.0,0.0,0.0,0.0,1